markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "ichengchao"

author: "charles"
atom-baseurl: "http://chengchao.name"
host: 0.0.0.0
navigations:
  - title: Archive
    class: fa fa-list-ul fa-lg
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user-secret
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

